labels:
- name: 'bug'
  color: 'EE0701'
- name: 'feature'
  color: '1D76DB'
- name: 'duplicate'
  description: 'Issue is a duplicate of another issue previously raised'
  color: 'CFD3D7'
- name: 'stale'
  description: 'Issue is no longer relevant or inactive'
  color: 'FAFAFA'